### ISSUE TITLE
ansible: usb connect timing lag

### ISSUE THREAD

**Issue by tehn** [monome/ansible#23]
investigate timing glitch on usb connect

**Comment by audionerd** [comment]
i’ve noticed this when ansible is clocked externally. connecting a grid (via switch) causes kria to freeze and miss a beat.

**Comment by csboling** [comment]
Sounds like this has been [https://llllllll.co/t/ansible-bug-reports-official/12436/52](investigated) some, the search is still on for older discussion of this.

**Comment by scanner-darkly** [comment]
found it: 

https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/281 
https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/285
https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/286

the experimental fix for it was commenting out this delay: 

https://github.com/monome/libavr32/blob/master/src/usb/ftdi/uhi_ftdi.c#L194

not sure what's the purpose of that delay (to let the rest of initialization happen properly probably?) and whether removing it fixes it for some grids but breaks it for some others.
