### ISSUE TITLE
Resetting velocity values on JF when exiting leader mode

### ISSUE THREAD

**Issue by imminentgloom** [monome/ansible#84]
Can anyone add “JF.VTR 0 10” to the procedure for exiting leader mode for Just Friends? 

This would ensure the module could return to the same state as before leader mode was active. Currently it remembers the lower volume from synth mode until the next power-cycle.

As discussed here:
https://llllllll.co/t/gremlins-on-the-i2c-bus-with-ansible-and-just-friends/32913

**Comment by csboling** [comment]
Thanks for pinging about this again, makes total sense. I recall seeing this post but it totally slipped my mind since then, apologies for the delay! Build going up shortly in the beta thread.

**Comment by imminentgloom** [comment]
Awesome!
